name: My First GitHub Action

on:
  push:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Hello Message
        run: echo "Hello from GitHub Actions!"

      - name: Show Date and Time
        run: date

      - name: Show Branch Name
        run: echo "Current Branch: master"

      - name: List Repository Files
        run: ls -la

      - name: Show Runner OS
        run: echo "Runner OS: $RUNNER_OS"
