name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment Environment"
        required: true
        default: staging

jobs:
  manual-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Selected Environment
        run: echo "Environment = ${{ github.event.inputs.environment }}"